<?php return array (
  'october\\demo\\Plugin' => 'plugins\\october\\demo\\Plugin.php',
  'backend\\Controllers\\index' => 'modules\\backend\\controllers\\index.php',
  'backend\\Controllers\\auth' => 'modules\\backend\\controllers\\auth.php',
  'cms\\Controllers\\index' => 'modules\\cms\\controllers\\index.php',
  'backend\\Controllers\\media' => 'modules\\backend\\controllers\\media.php',
  'system\\Controllers\\settings' => 'modules\\system\\controllers\\settings.php',
  'backend\\Controllers\\users' => 'modules\\backend\\controllers\\users.php',
  'cms\\Controllers\\themes' => 'modules\\cms\\controllers\\themes.php',
  'system\\Controllers\\updates' => 'modules\\system\\controllers\\updates.php',
  'backend\\Controllers\\userroles' => 'modules\\backend\\controllers\\userroles.php',
  'anandpatel\\wysiwygeditors\\Plugin' => 'plugins\\anandpatel\\wysiwygeditors\\Plugin.php',
  'AnandPatel\\WysiwygEditors\\Models\\Settings' => 'plugins\\anandpatel\\wysiwygeditors\\models\\Settings.php',
  'AnandPatel\\WysiwygEditors\\FormWidgets\\Editor' => 'plugins\\anandpatel\\wysiwygeditors\\formwidgets\\Editor.php',
  'cms\\Controllers\\themeoptions' => 'modules\\cms\\controllers\\themeoptions.php',
  'axmit\\storage\\Plugin' => 'plugins\\axmit\\storage\\Plugin.php',
  'buzzwordcompliant\\dbcontent\\Plugin' => 'plugins\\buzzwordcompliant\\dbcontent\\Plugin.php',
  'buzzwordcompliant\\dbcontent\\Controllers\\staticblocks' => 'plugins\\buzzwordcompliant\\dbcontent\\controllers\\staticblocks.php',
  'BuzzwordCompliant\\DBContent\\Models\\StaticBlock' => 'plugins\\buzzwordcompliant\\dbcontent\\models\\StaticBlock.php',
  'BuzzwordCompliant\\DBContent\\Components\\StaticBlock' => 'plugins\\buzzwordcompliant\\dbcontent\\components\\StaticBlock.php',
  'anandpatel\\seoextension\\Plugin' => 'plugins\\anandpatel\\seoextension\\Plugin.php',
  'AnandPatel\\SeoExtension\\Models\\Settings' => 'plugins\\anandpatel\\seoextension\\models\\Settings.php',
  'AnandPatel\\SeoExtension\\Components\\BlogPost' => 'plugins\\anandpatel\\seoextension\\components\\BlogPost.php',
  'AnandPatel\\SeoExtension\\Components\\StaticPage' => 'plugins\\anandpatel\\seoextension\\components\\StaticPage.php',
  'AnandPatel\\SeoExtension\\Components\\CmsPage' => 'plugins\\anandpatel\\seoextension\\components\\CmsPage.php',
);